const NewsDummyData = [
  {
    id: 1,
    title: "mollit ad tempor voluptate eiusmod",
    innerText:
      "Duis eu tempor culpa reprehenderit qui eiusmod irure eu. Cillum ea et Lorem commodo. Nisi duis minim ullamco elit sunt ex. Exercitation consectetur duis elit ex labore deserunt consectetur sunt veniam adipisicing amet amet pariatur.\r\nNulla Lorem labore culpa ex commodo Lorem eu anim tempor reprehenderit ipsum elit. Est aute aute et incididunt eu eu occaecat aliquip ad. Cillum ut ut proident adipisicing aliqua.\r\nEsse voluptate ipsum et cupidatat minim dolore adipisicing quis id. Eiusmod qui eiusmod ad veniam aute Lorem aliqua ex. Laboris laborum ad nisi nisi exercitation non duis id anim in in.\r\nAdipisicing nostrud elit incididunt cupidatat exercitation est non culpa. Magna esse voluptate anim sint quis minim nisi in nisi. Aliquip dolore minim consequat dolore magna anim exercitation irure nisi ea velit nostrud incididunt. Id eiusmod ullamco proident occaecat non. Magna dolore do id eiusmod sit excepteur voluptate.\r\nLaboris id commodo voluptate velit magna anim deserunt enim consequat officia mollit sint fugiat. Quis eiusmod labore adipisicing ex non incididunt id ut aliquip proident. Aliquip mollit irure id excepteur ad nulla dolore non pariatur voluptate esse deserunt et. Officia laborum qui qui laborum deserunt voluptate. Reprehenderit tempor reprehenderit cupidatat cillum laborum.\r\nIn nostrud esse officia deserunt magna culpa reprehenderit non deserunt officia aliqua nostrud id voluptate. Nulla amet elit occaecat culpa anim labore veniam officia. Irure consectetur aute culpa voluptate enim non mollit non minim esse labore nostrud pariatur. Velit irure aute mollit duis qui adipisicing commodo.\r\n",
    section: {
      id: 1,
      name: "finance",
    },
  },
  {
    id: 2,
    title: "cillum incididunt do esse nulla",
    innerText:
      "Ullamco cupidatat nostrud enim nisi amet fugiat do aute dolor et exercitation. Consectetur commodo Lorem aute minim ut esse Lorem exercitation reprehenderit sint cillum ut. Laboris irure id voluptate duis id minim ipsum ipsum ut. Sit nulla aute ea cillum commodo officia enim nostrud dolor minim non dolor. Et aute Lorem et reprehenderit velit occaecat nostrud culpa non Lorem anim. Laborum id magna quis reprehenderit ea in. Velit qui anim eiusmod incididunt consectetur labore.\r\nEnim reprehenderit fugiat ad elit excepteur consequat dolor mollit. Eiusmod proident sit tempor enim ut ullamco cillum ut. Officia culpa veniam sit quis dolore ex minim reprehenderit anim ea nulla excepteur reprehenderit Lorem.\r\nEiusmod ex irure do incididunt deserunt veniam do. Ad elit duis aliquip aliquip. Duis Lorem et do sit id magna sunt incididunt cillum. Irure sint excepteur incididunt ad in eiusmod commodo ex eu deserunt laboris occaecat commodo. Elit consectetur fugiat quis dolor eu Lorem elit culpa reprehenderit.\r\nEnim cillum adipisicing ex proident. Exercitation nisi voluptate culpa labore nisi aliqua in amet qui. Ex consectetur ex cupidatat reprehenderit consequat incididunt elit. Qui ex elit dolor voluptate ullamco nisi. Ullamco consequat consequat fugiat reprehenderit culpa. Minim cupidatat nisi in et duis. Ad mollit laborum proident amet id excepteur esse.\r\nNulla incididunt voluptate ullamco labore labore. Reprehenderit amet occaecat eiusmod magna. Pariatur in quis ullamco dolor sunt aliqua eiusmod anim occaecat laboris voluptate.\r\nVeniam irure dolore anim cupidatat occaecat qui esse. Fugiat nisi officia id officia minim proident aute consequat ipsum sint sit occaecat. Excepteur dolore adipisicing amet do nisi velit. Do tempor nulla enim consequat non qui eiusmod voluptate commodo. Ea id culpa mollit voluptate amet. Exercitation amet commodo nostrud ea mollit enim. Voluptate duis irure deserunt elit deserunt eu exercitation qui sint aliqua amet voluptate consequat tempor.\r\n",
    section: {
      id: 5,
      name: "traveling",
    },
  },
  {
    id: 3,
    title: "minim veniam amet enim ullamco",
    innerText:
      "Anim nostrud adipisicing ut anim aliquip dolore eiusmod consequat irure adipisicing incididunt. Quis enim eu magna ea anim irure eiusmod incididunt voluptate culpa sunt. Ipsum incididunt ut fugiat adipisicing sit sit fugiat. Ex exercitation nisi fugiat qui excepteur qui nostrud laboris nisi consectetur cupidatat laboris. Fugiat duis id id Lorem officia reprehenderit ullamco do incididunt laborum veniam sit Lorem aute. Excepteur aliqua adipisicing do et est deserunt deserunt in ullamco.\r\nAute est ipsum laborum nostrud sunt quis sit nostrud commodo. Lorem excepteur duis amet sit fugiat amet. Nulla quis consequat ipsum pariatur ad elit laboris culpa ipsum consequat deserunt culpa.\r\nAnim deserunt sit qui laboris laborum quis in. Elit deserunt nostrud Lorem dolore sint sint nisi mollit ipsum in. Dolor proident cillum ex minim incididunt duis ipsum. Do id culpa velit laboris voluptate cupidatat laboris voluptate commodo exercitation. Excepteur nisi consectetur proident irure Lorem ullamco sunt. Consequat esse eu dolore esse deserunt minim est elit veniam est culpa. Qui dolore esse quis pariatur dolor est voluptate fugiat laborum.\r\nDolor commodo adipisicing id amet nisi consectetur voluptate sit. Esse id non aute labore mollit veniam deserunt est ipsum laborum labore sunt. Eu cupidatat laborum tempor in dolor consequat sint nostrud Lorem non pariatur. Aute dolore in ad sit dolore. Esse tempor fugiat exercitation consectetur consectetur dolore cillum laborum culpa consectetur quis culpa quis occaecat.\r\nLabore minim velit mollit esse dolor. Proident nisi incididunt non sint commodo officia fugiat nostrud occaecat qui. Cupidatat aliqua adipisicing labore sit minim quis duis magna voluptate duis voluptate elit.\r\nConsectetur cillum dolore anim excepteur nulla anim ut sint occaecat. Laboris ea mollit occaecat enim Lorem anim ullamco cupidatat consequat deserunt in eiusmod esse sunt. Ex minim duis consectetur enim cillum sunt consectetur. Reprehenderit occaecat adipisicing aliqua sint. Nulla esse non irure ipsum do nulla incididunt voluptate sunt.\r\n",
    section: {
      id: 4,
      name: "politics",
    },
  },
  {
    id: 4,
    title: "duis incididunt dolor dolore aliqua",
    innerText:
      "Proident aute ad adipisicing veniam culpa consequat excepteur. Labore ex anim dolore ex aliqua proident elit elit aliquip esse veniam irure labore. Non laborum qui eu eu nostrud irure quis culpa Lorem sunt cillum eiusmod. Occaecat eu Lorem magna incididunt reprehenderit do pariatur. Fugiat fugiat sint sit occaecat consectetur adipisicing eiusmod ad officia ad mollit amet in mollit.\r\nCulpa cillum duis consectetur officia ullamco reprehenderit ipsum consequat laboris in exercitation deserunt. Occaecat deserunt laboris irure voluptate officia mollit eu quis non aliquip non. Aliqua tempor culpa cillum proident. Lorem nostrud eu consectetur labore laborum. Ullamco nisi occaecat dolor reprehenderit ex irure.\r\nIpsum labore minim commodo minim nulla veniam cupidatat aute minim eiusmod nisi aute quis eu. Adipisicing id ad id adipisicing velit dolore excepteur. Ad adipisicing ut cillum eiusmod culpa culpa reprehenderit. Commodo consequat id ea esse nisi incididunt eu aliquip sint in veniam voluptate.\r\nDolore id anim dolor nisi non dolor sit pariatur nostrud velit cupidatat incididunt id. Elit duis proident culpa anim irure magna sint et veniam anim deserunt velit culpa. Eu consectetur occaecat cillum fugiat ipsum nisi reprehenderit consequat fugiat. Ullamco fugiat voluptate sit minim reprehenderit laborum qui nostrud mollit tempor. Elit velit enim sunt dolor in consectetur commodo cillum sit eiusmod amet culpa mollit. Ad reprehenderit qui ipsum nostrud sunt do ex.\r\nSit Lorem voluptate do magna consequat eiusmod cillum qui. Incididunt et enim nulla occaecat culpa sit quis. Magna laboris pariatur magna ex consectetur. Culpa incididunt officia anim sint culpa aliqua Lorem sunt adipisicing officia laborum laborum veniam nulla. Magna ullamco esse laboris nostrud excepteur reprehenderit cupidatat aliqua voluptate do aute ex eiusmod Lorem.\r\nSunt do adipisicing quis labore excepteur dolore sunt adipisicing ad adipisicing deserunt voluptate. Sit eiusmod aliquip eu in sint tempor est ullamco quis laboris esse dolore aliquip anim. Dolor in sunt ipsum enim enim laboris consectetur ullamco excepteur aliquip ea adipisicing velit.\r\n",
    section: {
      id: 1,
      name: "traveling",
    },
  },
  {
    id: 5,
    title: "cillum in veniam dolore commodo",
    innerText:
      "Ipsum irure consequat occaecat enim nostrud incididunt in esse anim laborum ullamco eu ex minim. Occaecat enim incididunt ea ut commodo laborum consequat mollit. Tempor eiusmod anim occaecat officia nulla et veniam esse sit commodo ad esse ullamco proident. Officia mollit Lorem irure do aute amet deserunt consequat et excepteur nulla. Exercitation pariatur irure velit reprehenderit incididunt pariatur amet sint consequat incididunt mollit exercitation culpa quis. Anim non sit esse labore incididunt voluptate officia reprehenderit ad magna. Pariatur est et aliquip ad sit occaecat velit et.\r\nVoluptate velit nisi officia veniam. Amet anim ipsum culpa in laborum. Cupidatat commodo dolore amet ad quis consectetur ex ad proident.\r\nLorem deserunt commodo occaecat magna aute magna ullamco. Voluptate fugiat adipisicing ex commodo anim dolore deserunt ad culpa consectetur cupidatat ad. Ipsum veniam irure irure adipisicing ullamco minim duis deserunt culpa cillum nisi aute nostrud. Adipisicing aute labore culpa minim sunt labore excepteur ipsum est. Proident quis culpa voluptate do Lorem reprehenderit Lorem elit. Voluptate eu non Lorem nulla do voluptate anim. Nulla duis est labore quis nisi officia laboris.\r\nEiusmod irure consectetur culpa reprehenderit consequat eiusmod proident Lorem incididunt voluptate labore cillum ea quis. Adipisicing in sint adipisicing est cillum nulla proident tempor esse eiusmod consectetur in. Cillum Lorem ex Lorem proident esse est quis.\r\nOfficia laborum enim commodo officia proident in Lorem dolor nostrud sint. Qui quis esse nostrud do. Nulla adipisicing tempor amet sit laboris mollit fugiat. Enim excepteur proident id nulla dolore quis anim nulla laboris dolore. Sunt aute ea id occaecat ullamco excepteur excepteur fugiat non duis occaecat ea. Aute aute commodo dolor consequat eiusmod id. Adipisicing non do duis anim id deserunt exercitation Lorem voluptate dolore culpa sint quis ut.\r\nEu veniam elit amet sint laborum consequat ex. Et reprehenderit in incididunt sunt do voluptate laboris id eu esse occaecat proident Lorem sunt. Minim ad exercitation est non. Elit dolor et minim id minim deserunt mollit irure dolor et nulla proident labore cillum. Labore ipsum eiusmod consectetur deserunt velit excepteur esse amet nulla aute. Sunt ea amet dolor in Lorem quis.\r\n",
    section: {
      id: 3,
      name: "politics",
    },
  },
  {
    id: 6,
    title: "duis ad veniam occaecat sunt",
    innerText:
      "Nostrud ex voluptate consectetur pariatur non nostrud incididunt excepteur magna magna quis ipsum. Incididunt exercitation ut veniam est. Amet id in ad eiusmod. Aliquip dolore ut in sint consectetur ut officia minim officia in cupidatat. Nostrud consequat consequat voluptate non consequat cupidatat elit pariatur eiusmod. Labore eu ullamco anim esse incididunt tempor Lorem pariatur irure occaecat sit elit culpa eu. Aute sit cillum tempor commodo exercitation.\r\nAliqua laboris ut nisi pariatur incididunt minim ad nisi consectetur ea mollit fugiat minim. Qui ullamco occaecat ex est reprehenderit nulla nostrud deserunt amet veniam dolor commodo exercitation. Incididunt in non eiusmod minim cillum aute.\r\nEx duis Lorem labore cupidatat. Tempor amet proident cillum non eu. Anim adipisicing ex duis eu id.\r\nLorem anim incididunt magna incididunt minim enim. Est nulla quis deserunt laboris sint id velit minim dolor deserunt commodo reprehenderit nostrud deserunt. Aliquip veniam cillum esse sint exercitation eu labore. Ad occaecat sunt fugiat quis ex reprehenderit nulla est cupidatat.\r\nNostrud adipisicing sit ipsum in ut. Cillum sit aliquip eu sit ullamco non tempor in culpa cillum id qui cupidatat ipsum. Velit minim veniam velit veniam sit consequat occaecat voluptate proident dolor. Ipsum ea eu laborum dolore culpa sit minim ea sunt aliqua reprehenderit nulla amet. Ipsum non tempor labore mollit voluptate eu enim aliquip fugiat do ea. Cillum officia do id culpa deserunt sunt culpa eu aliqua est aliqua ea officia. Laboris velit laborum ex reprehenderit sunt dolor.\r\nIrure ullamco consectetur pariatur ut. Culpa ad culpa exercitation commodo ut reprehenderit anim aute sunt nostrud sint incididunt mollit anim. Nostrud culpa in consectetur quis consequat amet. Sunt labore voluptate veniam exercitation mollit deserunt excepteur ut consectetur proident ea velit et commodo. Aute magna anim et irure.\r\n",
    section: {
      id: 5,
      name: "politics",
    },
  },
  {
    id: 7,
    title: "occaecat ullamco consectetur nisi enim",
    innerText:
      "Ex Lorem est eiusmod consectetur. Quis voluptate magna enim aute mollit officia elit esse. Officia in qui officia nulla cupidatat velit cupidatat eu ullamco est labore incididunt nostrud. Anim nisi in qui aliquip adipisicing non amet nostrud irure esse dolor Lorem. Incididunt aute incididunt mollit nisi sunt irure occaecat ea reprehenderit ipsum. Eiusmod eiusmod est deserunt ex incididunt laborum.\r\nLabore mollit laboris duis nostrud enim mollit excepteur ipsum laboris. Non laboris amet consequat enim. Id ullamco consectetur consequat id et ex.\r\nQui velit id ea consectetur nisi ut. Cupidatat officia aliqua duis elit minim quis occaecat et. Id aliqua amet commodo voluptate exercitation aliquip consectetur veniam velit. Est Lorem aliquip voluptate id cupidatat non sit anim ad. Laboris est magna laboris nisi cupidatat proident proident nisi nostrud nisi esse cillum ut.\r\nLaborum elit culpa irure officia eu elit enim ex id id labore. Proident adipisicing elit excepteur duis pariatur adipisicing pariatur cupidatat ut. Nostrud excepteur id velit et do cillum deserunt qui irure labore. Nulla Lorem anim proident non consequat velit ex dolor.\r\nNulla consequat et Lorem eiusmod non. In commodo minim excepteur ipsum in mollit eu magna eiusmod excepteur. Ea ipsum ex duis est eiusmod magna proident magna est duis. Laboris duis tempor eiusmod sint laborum laborum sit eiusmod et consectetur ullamco anim aliquip. Adipisicing esse enim culpa amet ipsum sit eiusmod magna mollit.\r\nTempor officia Lorem et sint excepteur in nisi ad nulla irure adipisicing. Esse exercitation cillum deserunt labore id ipsum esse laboris aute minim incididunt consequat aute. Esse ea dolor dolore et non in voluptate fugiat anim aute. Eiusmod aliquip commodo quis minim officia laborum pariatur eiusmod do. Et deserunt et culpa do nostrud officia id amet laborum. Anim pariatur esse quis ad in.\r\n",
    section: {
      id: 1,
      name: "traveling",
    },
  },
  {
    id: 8,
    title: "cillum exercitation anim velit sunt",
    innerText:
      "Consequat consectetur nostrud enim dolore amet fugiat sunt irure non. Est ut occaecat duis dolore incididunt consequat reprehenderit Lorem. Minim veniam pariatur occaecat veniam ea aliqua nisi aliqua velit fugiat laborum. Culpa ad non sunt est fugiat culpa ipsum mollit magna do laborum.\r\nNon in velit veniam commodo pariatur aliquip sit Lorem occaecat eiusmod nostrud proident. Ullamco incididunt ad aliquip velit occaecat incididunt aute dolor. Dolore est excepteur adipisicing et cillum quis eiusmod veniam ut enim. Duis dolor commodo ex commodo enim dolor elit irure esse in velit. Minim magna ullamco commodo sit dolor voluptate. Cillum ut laborum anim fugiat irure velit dolore amet. Cupidatat eiusmod commodo esse laboris do voluptate sit sunt occaecat pariatur sint enim ad.\r\nEiusmod ipsum eu voluptate esse dolore ea ullamco culpa eu enim nulla mollit laborum excepteur. Amet sit excepteur tempor aute excepteur voluptate dolore minim sit eu. Reprehenderit nulla dolore nulla velit labore sit. Sunt anim anim laborum et ullamco.\r\nVelit ullamco fugiat irure labore esse ea aliquip eiusmod occaecat ad. Consectetur cillum pariatur voluptate nulla officia excepteur Lorem excepteur do dolor. Esse velit nisi incididunt do veniam aliquip irure elit est veniam sint magna amet deserunt. Est enim minim mollit culpa culpa ad nisi incididunt aliqua nisi Lorem. Cupidatat nisi enim commodo do consectetur magna anim quis cupidatat duis non. Id culpa dolore exercitation velit ex ipsum dolore do elit velit aliqua laborum. Fugiat culpa cillum dolore ad id dolor fugiat occaecat Lorem.\r\nElit tempor ullamco eiusmod et duis qui qui cillum eu. Quis quis id pariatur ut nisi sunt qui nulla duis aliqua ullamco ullamco. In sit labore ad aliquip eiusmod commodo non mollit anim. Mollit exercitation veniam elit voluptate eiusmod in. Lorem elit ullamco officia dolor non aliquip deserunt dolore elit minim aute officia.\r\nSit ex eu duis consectetur laborum consequat. Cupidatat velit nisi in elit culpa sint nulla id reprehenderit deserunt dolore nisi adipisicing id. Enim proident amet ipsum elit tempor mollit veniam. Esse amet et in fugiat proident aliqua ullamco culpa. Elit nulla ullamco id id voluptate sint ullamco. Tempor exercitation fugiat qui fugiat sunt amet nisi. Nulla qui cupidatat sit minim incididunt dolore anim commodo cupidatat magna esse.\r\n",
    section: {
      id: 5,
      name: "digest",
    },
  },
  {
    id: 9,
    title: "veniam mollit velit amet ullamco",
    innerText:
      "Nulla ad dolor officia commodo ex ipsum adipisicing non pariatur. Esse eu proident aliqua id. Do ut et pariatur ex Lorem laborum nisi dolor. Laborum reprehenderit voluptate mollit laboris nulla cillum laboris in qui. Ad eiusmod ex fugiat ullamco labore deserunt. Ad Lorem minim commodo excepteur magna cupidatat in deserunt eiusmod incididunt.\r\nDeserunt consectetur occaecat ex qui esse fugiat ullamco duis ipsum est excepteur deserunt ex dolor. Officia laborum commodo excepteur tempor nisi voluptate reprehenderit ipsum. Qui consequat mollit deserunt nostrud enim qui pariatur ex sunt irure adipisicing duis adipisicing sit. Veniam deserunt pariatur minim ad aute pariatur Lorem adipisicing nisi ipsum mollit magna proident. Ea et adipisicing incididunt deserunt ex. Velit esse laborum duis consectetur pariatur laborum ullamco. Deserunt id magna nisi sint nostrud culpa aute enim.\r\nNostrud quis nulla proident adipisicing anim. Adipisicing amet dolor laborum adipisicing culpa nisi anim tempor minim qui tempor adipisicing reprehenderit. Duis irure commodo exercitation eu ea ullamco proident laborum exercitation.\r\nDuis ex sint occaecat sit enim ea aute laborum proident laborum. Consequat commodo id do aliquip incididunt adipisicing laborum voluptate. Enim id tempor ullamco non nisi. Dolor non qui est mollit ad. Dolore do esse do mollit commodo reprehenderit reprehenderit. Consectetur ea ipsum excepteur quis sint velit minim.\r\nAliquip id officia amet eiusmod pariatur aliqua nostrud tempor reprehenderit ipsum culpa minim. Mollit et et pariatur do Lorem. Laboris amet excepteur adipisicing amet proident.\r\nAmet elit nulla qui proident sunt occaecat ex officia sint nulla nisi officia laborum. Reprehenderit et anim officia veniam amet ut nostrud ut. Non officia Lorem qui tempor elit est. Cillum cupidatat tempor consequat aliquip adipisicing esse. Esse nulla veniam adipisicing pariatur. Aliquip enim amet incididunt tempor laborum et qui amet culpa amet eu nisi.\r\n",
    section: {
      id: 3,
      name: "digest",
    },
  },
  {
    id: 10,
    title: "esse incididunt cillum magna amet",
    innerText:
      "Anim eiusmod incididunt veniam ex ad est qui pariatur laborum veniam Lorem labore. Labore magna velit proident consequat ullamco sunt adipisicing cillum occaecat sit elit commodo. Nostrud duis esse est exercitation proident ullamco. Cupidatat officia consectetur reprehenderit do aute est. Quis voluptate id non cillum anim labore occaecat laborum do minim aliquip dolor ad laboris.\r\nMinim exercitation et anim excepteur nulla labore. Adipisicing magna labore elit Lorem duis duis enim sunt quis consectetur. Nostrud deserunt ullamco irure sint irure nostrud elit aliqua mollit anim adipisicing. Aliqua est adipisicing amet qui proident quis. Irure ut quis et consequat cillum esse.\r\nMollit deserunt fugiat occaecat dolore elit culpa ex nostrud exercitation velit consectetur dolor culpa dolor. Esse elit quis aute laboris labore qui sunt adipisicing officia tempor eu minim. Tempor ex id velit Lorem ut proident exercitation consectetur sit cillum. Ut non mollit est adipisicing proident consectetur Lorem proident deserunt fugiat quis duis reprehenderit. Exercitation qui eu proident culpa mollit veniam. Sunt do laboris sit sint incididunt fugiat excepteur qui dolor exercitation fugiat. Velit ut dolor cupidatat sunt reprehenderit sit.\r\nMollit est deserunt officia aute nulla. Lorem labore pariatur non magna occaecat eiusmod voluptate ad nisi cupidatat incididunt. Reprehenderit mollit enim proident qui nostrud nulla commodo irure esse.\r\nConsectetur laboris reprehenderit qui fugiat ullamco eiusmod ex ex ad nulla consectetur velit quis aliquip. Id veniam nulla tempor aute irure qui cillum sit. In consequat aliqua dolor dolor velit ullamco ullamco cupidatat sint fugiat aliquip irure pariatur.\r\nEt Lorem labore labore reprehenderit deserunt velit sunt tempor. Id duis adipisicing sit ipsum magna cupidatat labore. Qui duis aliquip do ut. Id ea cupidatat excepteur laboris amet quis aute elit magna.\r\n",
    section: {
      id: 5,
      name: "digest",
    },
  },
  {
    id: 11,
    title: "velit mollit veniam officia est",
    innerText:
      "Laboris ex ex officia est. Incididunt in qui dolore in ea culpa. Aute sit voluptate pariatur incididunt deserunt elit non pariatur qui ut aliqua sint in excepteur. Reprehenderit elit aute sit amet nulla consequat dolore. Cupidatat qui ullamco ullamco nisi aliqua id. Aute elit do nostrud occaecat sint cupidatat ad nostrud fugiat laborum.\r\nSint elit enim culpa tempor sit veniam reprehenderit laborum laborum laborum cillum. Eu nulla id ullamco non adipisicing fugiat. Reprehenderit culpa culpa Lorem reprehenderit excepteur incididunt adipisicing anim sunt ex adipisicing non. Lorem consequat non magna voluptate. Cupidatat velit excepteur anim nisi voluptate reprehenderit non aute tempor ipsum exercitation. Esse aute irure id irure excepteur pariatur tempor ad duis. Enim in eiusmod consequat ea sint enim enim nostrud culpa aute.\r\nNon eu ipsum incididunt deserunt qui non labore exercitation ut culpa tempor ipsum irure. Aliquip fugiat veniam aliqua occaecat laborum aute qui dolor cupidatat adipisicing cupidatat qui. Non commodo nulla deserunt sit consequat excepteur aliqua duis ullamco labore. Esse sint labore ex in esse tempor laborum laboris. Sint ullamco reprehenderit et id nostrud cupidatat duis aliquip. Anim eiusmod ipsum aute occaecat velit. Magna irure deserunt proident eu do et.\r\nIn elit adipisicing aliquip elit pariatur irure nulla consectetur proident laboris velit ad Lorem occaecat. Excepteur elit exercitation nulla tempor enim exercitation dolore excepteur qui. Ex ad dolor pariatur velit qui occaecat. Ea consectetur nostrud sunt do laboris qui culpa adipisicing dolor aliquip. Ipsum mollit enim eu sit mollit.\r\nConsectetur aute excepteur dolore proident est. Tempor culpa aliqua ea irure occaecat. Qui minim velit cillum elit esse in deserunt laborum adipisicing est ex laborum anim. Occaecat do occaecat consectetur sit irure sint proident sunt.\r\nElit nisi sint sit eu magna nostrud dolore. Fugiat culpa anim cupidatat cupidatat non proident. Mollit Lorem ex excepteur eiusmod irure excepteur sit aute excepteur officia aliqua labore consectetur. Esse ut occaecat laborum duis enim proident qui ullamco cillum.\r\n",
    section: {
      id: 5,
      name: "digest",
    },
  },
  {
    id: 12,
    title: "occaecat reprehenderit sit pariatur ex",
    innerText:
      "Ipsum sunt laborum nisi veniam magna labore. Elit tempor fugiat enim occaecat ipsum nulla Lorem minim eiusmod sit sit dolor qui. Cillum irure aute tempor reprehenderit. Ipsum tempor incididunt ut cupidatat ipsum. Ex nostrud nulla et cupidatat dolor qui.\r\nCupidatat magna veniam irure deserunt laboris deserunt. Ex in veniam minim aliquip reprehenderit tempor tempor. Ea ex esse exercitation ipsum culpa sint elit in eiusmod eiusmod officia culpa. Ipsum commodo aliqua exercitation est non enim velit ut amet. Aliquip cillum deserunt duis ipsum occaecat labore nostrud Lorem sint sit laborum proident aliquip ad.\r\nDolore aute magna irure fugiat eu quis tempor duis fugiat labore qui tempor velit. Lorem dolor mollit anim non enim non incididunt sit deserunt incididunt proident. Aute dolor incididunt irure proident eu consequat. Voluptate ut proident Lorem labore nostrud nostrud voluptate sint fugiat eiusmod ea ex.\r\nMollit voluptate ad nostrud nisi ipsum duis excepteur aliquip officia incididunt. Ipsum culpa velit pariatur consequat pariatur officia et excepteur. Labore amet sunt cillum exercitation. Elit exercitation qui excepteur ipsum duis occaecat qui velit voluptate. Sunt eu ullamco id nulla proident incididunt velit eu cillum ut irure sunt id ipsum. Ullamco ad veniam amet occaecat excepteur nostrud sint incididunt dolor ut veniam ipsum adipisicing. Ipsum deserunt duis elit dolore voluptate id.\r\nOccaecat voluptate ad in sunt esse amet non voluptate proident nisi proident nulla pariatur occaecat. Dolore quis irure fugiat exercitation consequat ut. Id occaecat Lorem et occaecat.\r\nEsse elit anim commodo eiusmod consequat in aute cillum dolore dolore dolore dolore. Minim nostrud eu qui duis incididunt qui velit excepteur adipisicing excepteur ut dolore ex ullamco. Irure ipsum eiusmod enim proident sit ad aliqua et tempor veniam ea deserunt qui qui. Reprehenderit culpa enim ut duis. Sit sint labore labore tempor ea minim deserunt do excepteur occaecat veniam exercitation. Lorem enim deserunt occaecat ea voluptate mollit esse in velit consequat duis quis consequat. Occaecat culpa dolor eiusmod amet velit velit non aliqua aliqua elit ex ea occaecat deserunt.\r\n",
    section: {
      id: 3,
      name: "traveling",
    },
  },
  {
    id: 13,
    title: "minim proident sit duis nostrud",
    innerText:
      "Occaecat adipisicing incididunt nulla officia enim aute mollit veniam consectetur do. Amet incididunt eu non minim nisi exercitation. Incididunt non cillum id excepteur voluptate non nostrud. Nisi eiusmod ut aute commodo aliqua sit do et ad consectetur enim. Laborum proident anim incididunt sint nostrud incididunt magna ut in pariatur eiusmod et ex consectetur. Do ex excepteur aliqua eiusmod veniam sint cillum irure aute reprehenderit nostrud. Mollit excepteur do cillum veniam minim et cillum irure ut ipsum.\r\nCillum incididunt voluptate eu velit incididunt ullamco. Sit cupidatat reprehenderit voluptate consequat commodo veniam adipisicing Lorem ad eu qui incididunt laborum adipisicing. Nostrud in excepteur eu amet irure eiusmod Lorem quis aliquip.\r\nMinim laborum dolor anim elit. Consectetur adipisicing amet exercitation consectetur elit consectetur laborum sunt dolor amet veniam pariatur voluptate. Sint dolor duis commodo mollit reprehenderit deserunt. Irure reprehenderit consectetur proident qui ea adipisicing incididunt pariatur nisi nulla ut dolore enim. Cillum cillum ipsum consequat tempor. Fugiat adipisicing cupidatat eu quis ea deserunt exercitation.\r\nExcepteur aute cillum ut id quis ex incididunt. Esse commodo voluptate aliqua ipsum cillum amet consectetur eiusmod. Enim fugiat fugiat qui enim aute do et proident sunt. Velit enim tempor ullamco ad incididunt incididunt in voluptate ullamco reprehenderit velit est.\r\nCulpa ut mollit consectetur laboris irure dolor commodo consectetur. Exercitation consequat nostrud occaecat occaecat qui nostrud nisi. Aliqua nostrud velit eiusmod exercitation do do sit duis ipsum. Non eu amet cupidatat aliqua Lorem veniam pariatur proident.\r\nMollit tempor id aute pariatur ea voluptate dolor tempor velit incididunt. Fugiat cupidatat culpa et sint in ut. Do deserunt fugiat ullamco magna ea excepteur. Labore fugiat tempor qui dolor duis ea tempor deserunt consectetur incididunt. Esse magna excepteur cillum dolor elit mollit.\r\n",
    section: {
      id: 4,
      name: "sport",
    },
  },
  {
    id: 14,
    title: "occaecat enim ut sit et",
    innerText:
      "Dolor id in pariatur magna irure nostrud et labore cillum. Laboris quis ipsum reprehenderit mollit ut fugiat pariatur mollit laboris excepteur. Laborum irure excepteur do ad nisi laborum proident veniam eu eu laboris commodo veniam. Voluptate ullamco pariatur tempor magna magna in irure voluptate commodo ut voluptate anim aliqua cupidatat. Aliquip aliqua velit quis in pariatur tempor dolore in proident ut enim incididunt.\r\nDuis aute esse ipsum tempor exercitation excepteur do. Lorem non adipisicing laboris excepteur ipsum culpa laborum irure est quis commodo ipsum. Labore qui anim esse voluptate aliquip adipisicing labore laborum. Quis ad exercitation qui sint tempor dolore occaecat ullamco cillum aliqua ea. Sit culpa laborum nisi aute magna in sit. Cillum ex sint elit ex cupidatat irure. Id reprehenderit consequat officia nisi tempor occaecat exercitation ex commodo.\r\nQui nulla non nisi quis. Non esse aliquip elit exercitation officia magna veniam deserunt exercitation deserunt adipisicing. Reprehenderit quis sint dolor velit et esse exercitation. Aliqua ex enim incididunt tempor. Mollit est pariatur cillum cupidatat minim irure eiusmod. Pariatur cupidatat non culpa ex.\r\nCillum reprehenderit qui commodo nulla do pariatur culpa tempor. Aliqua cupidatat enim occaecat pariatur sint eiusmod incididunt ex deserunt esse consectetur nostrud est ea. Ex fugiat reprehenderit veniam deserunt aliquip voluptate aute exercitation ea esse laborum in irure. Fugiat adipisicing mollit labore nostrud magna reprehenderit elit sit. Ut qui anim ad ipsum in in magna amet ullamco sit sint tempor consectetur. Laboris aliquip enim laboris in in aliquip in exercitation veniam nostrud consectetur.\r\nDo nisi nulla ullamco eu. Amet anim enim tempor consequat non qui excepteur sint pariatur. In excepteur fugiat ad ad occaecat ut Lorem aute. Laboris enim ipsum cupidatat commodo duis qui ex sunt sunt non. Adipisicing quis duis culpa ea. Occaecat eu magna voluptate magna fugiat magna sint nulla irure.\r\nDo aute adipisicing eu laborum. Aliquip pariatur amet enim minim nostrud nulla. Ex ex ea quis minim. Esse reprehenderit reprehenderit amet magna sit nostrud exercitation exercitation irure laboris officia. In eu veniam incididunt enim consequat ullamco. Cupidatat aute quis labore do proident consectetur incididunt commodo amet non amet do ex nulla. Labore dolore esse id incididunt amet laboris eiusmod dolore eu incididunt dolor et culpa.\r\n",
    section: {
      id: 4,
      name: "politics",
    },
  },
  {
    id: 15,
    title: "ex nisi et ullamco aliquip",
    innerText:
      "Laborum sit sit aliqua id do laborum sunt mollit sunt magna tempor non. Id voluptate ullamco et cillum dolor non. Eu elit aute incididunt ipsum. Incididunt irure consequat mollit magna exercitation nisi incididunt tempor officia id. Consectetur tempor aute minim ea eiusmod nisi ullamco reprehenderit voluptate adipisicing nulla.\r\nAd aliqua qui cupidatat mollit quis est quis eiusmod qui dolor. Consequat do ullamco enim minim consequat aliquip sit enim excepteur do dolor et proident. Ut excepteur aliqua excepteur occaecat cillum qui esse nisi. Est veniam officia consequat consectetur culpa amet sit non cupidatat incididunt laboris cupidatat consequat.\r\nDuis cillum ut nulla pariatur voluptate tempor mollit cupidatat incididunt ea proident elit Lorem. Lorem enim consequat pariatur ex excepteur laborum officia nisi minim et est tempor minim aute. Consectetur mollit aliquip cupidatat ullamco consectetur exercitation. Veniam fugiat cillum non non enim esse cupidatat. Esse incididunt ea laborum laboris commodo eiusmod anim.\r\nElit cupidatat labore do irure cillum enim consequat aliquip nostrud cupidatat amet exercitation dolore amet. Ullamco eiusmod deserunt et amet cillum ipsum aliqua sit proident esse. Sit labore nulla ex eu minim cupidatat labore magna ex aliqua aliqua.\r\nOfficia velit officia exercitation nisi. Deserunt reprehenderit exercitation enim proident aute id ex proident irure ex do. Enim consectetur voluptate enim quis amet dolor ipsum sint officia est non ea velit culpa. Aliqua ex pariatur dolor incididunt ipsum eu dolore ea consectetur officia dolore velit ea. Et dolor laboris incididunt ipsum labore veniam irure eu adipisicing labore. Velit incididunt culpa dolore aliquip nostrud cillum. Ipsum ut consequat excepteur Lorem.\r\nIn nulla cillum nisi esse ipsum pariatur adipisicing. Lorem sunt commodo eu adipisicing nulla est sunt elit non pariatur tempor elit veniam. Sunt laborum id reprehenderit nulla ad et tempor pariatur. Amet minim in proident magna mollit commodo occaecat esse.\r\n",
    section: {
      id: 3,
      name: "sport",
    },
  },
  {
    id: 16,
    title: "non veniam esse fugiat quis",
    innerText:
      "Exercitation minim do ea ea irure sint exercitation sunt id veniam eu elit culpa ipsum. Duis aliquip adipisicing aliqua do anim. Quis laboris eiusmod duis officia esse eiusmod adipisicing aliquip. Velit sunt ad mollit officia occaecat deserunt minim mollit.\r\nAute elit ullamco et fugiat ut dolore laborum in. Dolor aute ad consequat in ut adipisicing velit nulla. Reprehenderit amet qui ut est laborum laboris cupidatat anim ut laboris magna officia ullamco duis. Labore magna fugiat aliqua adipisicing qui laborum. In deserunt non in culpa ipsum magna Lorem tempor tempor sint exercitation et nostrud exercitation. Labore sunt aliqua reprehenderit excepteur sint velit non magna aute fugiat duis incididunt.\r\nDeserunt do incididunt consectetur cupidatat culpa. In pariatur Lorem anim dolore eiusmod cillum dolore enim cupidatat culpa reprehenderit qui adipisicing. Ex do nisi officia cupidatat culpa deserunt laboris quis aute ipsum. Nulla eu nisi enim sint ullamco quis eiusmod labore cillum aliquip irure excepteur. Aute dolore ad consectetur fugiat esse ea amet eiusmod elit non mollit ullamco adipisicing. Qui occaecat in elit cillum exercitation Lorem commodo velit commodo enim est ullamco.\r\nOfficia consectetur ut cupidatat minim ut. Officia adipisicing aute voluptate culpa et irure velit exercitation dolore. Reprehenderit ipsum dolore non reprehenderit amet tempor dolor aliqua incididunt id anim ut nisi voluptate. Id id incididunt eiusmod laboris ad anim anim nulla cupidatat. Quis proident mollit culpa ex exercitation.\r\nSunt amet incididunt officia voluptate elit ut sint sunt est labore Lorem. Mollit aliqua eiusmod sit dolor et. Incididunt sint labore veniam pariatur reprehenderit eu incididunt voluptate nostrud ea proident sit. Esse nisi elit cupidatat aliqua Lorem eu velit ut elit laborum amet id mollit eu.\r\nQuis et esse ex eu labore ut magna laborum. Ipsum ad qui do nisi ullamco. Adipisicing eu adipisicing ipsum ipsum commodo incididunt. Exercitation excepteur laborum laboris non voluptate veniam aliquip mollit consequat consequat non est proident. Voluptate fugiat veniam reprehenderit dolore ut velit reprehenderit deserunt est. Occaecat velit laboris do adipisicing enim.\r\n",
    section: {
      id: 5,
      name: "sport",
    },
  },
  {
    id: 17,
    title: "sint nisi duis cillum amet",
    innerText:
      "Sunt incididunt esse cupidatat laboris dolore est nostrud laborum. Amet aute id irure exercitation exercitation anim nulla minim laborum pariatur fugiat. Minim irure pariatur laboris labore laboris sit tempor.\r\nTempor qui ipsum ipsum tempor ad. Duis laboris cupidatat veniam nostrud proident in consectetur consectetur consequat proident proident mollit. Deserunt et amet amet excepteur elit laboris nisi ex ut eu culpa. Eu ullamco ea voluptate est exercitation reprehenderit proident amet dolore adipisicing consequat culpa. Labore occaecat occaecat laborum aute incididunt ullamco dolore nulla elit. Proident fugiat minim ea id aliqua officia tempor minim enim dolor sint magna.\r\nMollit Lorem est irure consequat ullamco quis proident Lorem aute aliqua tempor quis dolor. Cillum eu laboris eu nostrud cillum elit adipisicing elit labore nisi ut Lorem ullamco sunt. Irure aute et aliqua nostrud et reprehenderit nostrud nulla adipisicing nostrud cupidatat deserunt. Consectetur nisi incididunt cillum tempor dolore ut id pariatur labore consequat sint.\r\nAdipisicing ipsum magna ex sint Lorem aliquip aute aute deserunt ut aute. Mollit laboris cillum voluptate nostrud adipisicing non deserunt magna laborum esse est dolor do adipisicing. Reprehenderit culpa mollit ullamco ea. Ut minim culpa esse proident eiusmod elit nostrud voluptate eu. Anim adipisicing deserunt mollit elit ullamco mollit.\r\nId anim proident minim adipisicing magna quis et Lorem non laboris tempor aliqua. Mollit nostrud consequat sunt enim labore. Ex eiusmod adipisicing qui est enim. Officia dolor esse fugiat sint incididunt pariatur id. Sit ea sit exercitation occaecat dolore non dolor mollit. Velit dolor quis non excepteur duis ex mollit voluptate ipsum nisi.\r\nIpsum est commodo magna est incididunt dolor magna ad fugiat laboris anim magna ullamco. Elit culpa Lorem sunt quis nisi commodo duis esse dolore pariatur excepteur ullamco. Minim ut enim dolore velit laborum occaecat incididunt sit mollit ullamco voluptate Lorem ipsum. Quis incididunt excepteur dolor magna qui pariatur duis nostrud veniam sunt dolore ut nulla et.\r\n",
    section: {
      id: 4,
      name: "politics",
    },
  },
  {
    id: 18,
    title: "tempor excepteur dolor deserunt laborum",
    innerText:
      "Id nostrud Lorem pariatur quis ut ipsum. Amet enim aliquip non magna magna mollit fugiat. Qui esse eiusmod aliquip do ad sunt sunt Lorem Lorem est incididunt sunt. Ad consectetur do ut qui laboris. Eiusmod laboris est amet sunt velit veniam mollit consequat nisi. Minim non ad consectetur eiusmod laboris. Velit nisi non consectetur elit eu consequat nisi excepteur enim.\r\nAliqua cupidatat est veniam laborum magna cupidatat velit. Aliqua aliquip aute nisi qui ex fugiat aute nisi esse nostrud dolor excepteur cupidatat. Ad laboris ea cupidatat proident incididunt tempor nisi. Dolor nulla ex magna anim consectetur esse. Labore magna esse mollit veniam non aute eu. Proident do est eiusmod cillum.\r\nLorem esse exercitation eu occaecat minim non nulla anim. Fugiat sint consectetur ipsum deserunt ut. Incididunt aliqua officia consectetur irure quis culpa officia in consequat labore ut officia consequat. Est ex aute ut exercitation nisi aute est sit. Id mollit ipsum est culpa enim deserunt minim voluptate ullamco. Mollit amet cupidatat ex duis elit mollit quis anim ullamco elit.\r\nVoluptate qui Lorem ipsum ea amet anim ipsum dolor adipisicing duis. Cillum id laborum enim sit magna labore nostrud mollit reprehenderit et id labore velit. Enim pariatur culpa ad minim enim aliquip exercitation ullamco labore. Elit dolor commodo officia voluptate minim occaecat velit cillum incididunt tempor. Tempor excepteur amet mollit culpa id sint fugiat ipsum aliquip nostrud irure labore ea excepteur.\r\nVoluptate nostrud cillum dolor esse reprehenderit nulla aliquip ad. In est in ex labore culpa laborum irure commodo eiusmod cillum reprehenderit mollit. Enim mollit incididunt pariatur officia nostrud aliqua qui non magna excepteur do sint ea.\r\nEst ipsum quis incididunt id sunt aliqua incididunt amet mollit esse. Consectetur aliqua cupidatat culpa magna fugiat in ullamco enim consequat Lorem officia esse proident velit. Ipsum ex reprehenderit officia cupidatat non voluptate. Enim consequat ex amet dolor. Duis ut consequat est dolore adipisicing cillum duis id tempor ea duis magna exercitation velit. Dolor labore cupidatat est qui commodo quis. Dolore nostrud id fugiat ex non dolor.\r\n",
    section: {
      id: 3,
      name: "traveling",
    },
  },
  {
    id: 19,
    title: "fugiat cillum fugiat ea labore",
    innerText:
      "Deserunt nostrud adipisicing aliqua aliqua est nostrud consequat minim et labore consectetur. Ex ea veniam ipsum labore in excepteur anim officia Lorem fugiat cillum do fugiat laborum. Esse eu consequat elit sit incididunt. Culpa laboris dolore eu magna ut culpa laboris irure nulla pariatur eu.\r\nIn et ex aute aliqua tempor officia eu nostrud eiusmod. Ut Lorem mollit eiusmod non ea minim eiusmod tempor velit ut laboris ut voluptate. Esse mollit et enim nisi tempor fugiat minim anim voluptate.\r\nUllamco anim consequat nostrud culpa. Ullamco eiusmod Lorem commodo nostrud deserunt commodo. Fugiat proident elit eu velit incididunt. Nostrud velit ad deserunt eiusmod elit esse ipsum sit. Qui irure ea Lorem adipisicing nulla excepteur reprehenderit nisi pariatur.\r\nNisi tempor aute in cillum id. Aliquip sit sint nostrud proident cupidatat voluptate incididunt nisi aute aute sit. Sunt amet nisi voluptate incididunt ad do consequat elit commodo officia. Officia labore pariatur magna laborum. Elit ullamco magna anim culpa anim dolor aliqua. Mollit qui deserunt cupidatat veniam. Officia ex aliqua enim magna ad mollit commodo anim non.\r\nMinim ea incididunt tempor ut reprehenderit. Culpa labore culpa elit sit proident anim id occaecat. Dolore cupidatat velit ipsum reprehenderit qui mollit dolore nostrud.\r\nVeniam deserunt tempor qui do aliquip dolor. Ipsum officia cupidatat veniam tempor qui ipsum id pariatur culpa quis tempor quis labore elit. Cillum quis magna labore magna magna tempor cillum aliqua anim tempor. Laborum magna sunt dolor sint voluptate aliqua aute reprehenderit Lorem veniam sit magna sint ea. Labore amet commodo ut velit aliquip aliqua proident amet ut consequat non. Laborum duis sint minim veniam et sit dolore tempor amet labore eu ex adipisicing.\r\n",
    section: {
      id: 1,
      name: "traveling",
    },
  },
  {
    id: 20,
    title: "incididunt sunt dolor veniam eiusmod",
    innerText:
      "Amet mollit sit culpa excepteur tempor tempor cupidatat quis irure. Aliqua dolore do voluptate voluptate. Aute ex aute ullamco id velit. Id anim minim ex enim nulla sint sit magna minim pariatur ad sint. Nisi veniam excepteur officia deserunt consequat ullamco. Sint ea laboris tempor minim ut. Et ipsum minim labore officia excepteur.\r\nCulpa non pariatur sint occaecat. Magna qui mollit velit excepteur deserunt magna dolore id irure. Ex deserunt duis tempor esse laboris elit sunt dolore reprehenderit labore sit deserunt. Ut cillum anim labore ut occaecat Lorem.\r\nCommodo commodo reprehenderit laboris nisi et commodo minim. Non laboris do est quis ipsum do cupidatat officia est id irure. Adipisicing ullamco non id enim. Minim laborum in aliqua labore excepteur minim aliqua sint do.\r\nLaborum fugiat aliqua duis cupidatat reprehenderit ut Lorem est deserunt consectetur occaecat tempor ullamco. Dolor est aliquip excepteur aliquip id consectetur dolore et. Esse duis et proident adipisicing aliqua amet mollit reprehenderit tempor ullamco. Occaecat Lorem incididunt anim anim consectetur. Et veniam mollit est eu ullamco pariatur nisi eiusmod ullamco sint officia.\r\nNostrud in laboris fugiat fugiat. Dolor cillum excepteur consectetur velit dolore qui sit eu non. Culpa ad cillum laboris est commodo deserunt enim incididunt. Tempor consectetur duis deserunt officia. Ex ea proident velit duis laboris ex nostrud deserunt.\r\nConsectetur tempor eu mollit esse sint laboris sit ipsum proident irure qui. Fugiat dolor tempor velit sunt in enim veniam anim commodo sit ut incididunt laboris cillum. Fugiat incididunt nulla voluptate cupidatat.\r\n",
    section: {
      id: 1,
      name: "politics",
    },
  },
];

export default NewsDummyData;
